services:
  postgres:
    image: postgres
    container_name: dashfintrack-api-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: samirabradinho
      POSTGRES_DB: dashfintrackapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  postgres-test:
    image: postgres
    container_name: dashfintrack-api-postgres-test
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: samirabradinho
      POSTGRES_DB: dashfintrackapp
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql

volumes:
  postgres_data:
  postgres_test_data:
